// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WiseApi;

namespace WiseApi.Migrations
{
    [DbContext(typeof(WiseContext))]
    partial class WiseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WiseDomain.DataProviderConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataProviderType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("WiseDomain.ReportConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DataProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Query")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TimeType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DataProviderId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("WiseDomain.ReportCustomParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("QueryId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("QueryValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ReportConfigurationId")
                        .HasColumnType("int");

                    b.Property<bool>("Required")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportConfigurationId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("WiseDomain.ReportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CustomParameterValues")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("QueryTimeFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan?>("QueryTimeLast")
                        .HasColumnType("time(6)");

                    b.Property<DateTime?>("QueryTimeTo")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("WiseDomain.ReportConfiguration", b =>
                {
                    b.HasOne("WiseDomain.DataProviderConfiguration", "DataProvider")
                        .WithMany()
                        .HasForeignKey("DataProviderId");
                });

            modelBuilder.Entity("WiseDomain.ReportCustomParameter", b =>
                {
                    b.HasOne("WiseDomain.ReportConfiguration", null)
                        .WithMany("CustomParameters")
                        .HasForeignKey("ReportConfigurationId");
                });

            modelBuilder.Entity("WiseDomain.ReportRun", b =>
                {
                    b.HasOne("WiseDomain.ReportConfiguration", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId");
                });
#pragma warning restore 612, 618
        }
    }
}
